### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by uselesswaifu** [corytortoise/DuelsPE#1]
I would like to help in the development of This Duels plugin and hope you can make me a collaborator

**Comment by Thunder33345** [comment]
You should just start by forking and opening a PR
for the time begin

**Comment by corytortoise** [comment]
Yea, I would rather avoid giving full access for now. This is because: 1) I don't know who you are or what your reputation is, and 2) Code quality is a concern, and I know nothing about your work.

You are completely free to make PRs for now. I am active, so as long as it is good, I will merge it.
