### ISSUE TITLE
CRITICAL Error

### ISSUE THREAD

**Issue by xinghao2003** [corytortoise/DuelsPE#7]
```
[19:41:39] [Server thread/CRITICAL]: Error: "Cannot use object of type pocketmine\utils\Config as array" (EXCEPTION) in "DuelsPE-master/src/corytortoise/DuelsPE/Main" at line 89
```

**Comment by corytortoise** [comment]
The plugin was never even remotely functional, but okay.

**Comment by YHC2538** [comment]
Yes I have this problem too please fix!!!

**Comment by Thunder33345** [comment]
u should put, PLS DONT USE THIS
IT'S NOT COMPLETED

**Comment by YHC2538** [comment]
Then why is it open for public??

**Comment by Thunder33345** [comment]
just because it is open for public dosent meant it is working

**Comment by YHC2538** [comment]
u make no sense...

**Comment by corytortoise** [comment]
It's open source so people can contribute or use my code as a reference. That's why Poggit strongly discourages plugins that aren't submitted for inspection.
